---
title: "nfl statistics"
author: "Maggie O'Brien"
date: "2023-02-22"
output: html_document
---
```{r}
  data_subset <- reactive({
    df %>%
      filter(Position %in% input$groups,
             Position %in% input$position_select)
  })
  
  output$plot1 <- renderPlot ({
    data_subset() %>% 
      filter(!is.na(Weight..lbs.), !is.na(Height..inches.)) %>%
      group_by(Position)%>%
      summarize(meanweight = mean(Weight..lbs.),
                meanheight= mean(Height..inches.)) %>%
      filter(Position %in% input$position_select) %>%
      ggplot(aes(x=meanweight, y=meanheight, size=(meanweight/meanheight), 
                 col=Position)) +
      geom_point() +
      labs(title = "Weight vs. Height per position",
           x = "Mean weight (lbs)", y = "Mean height (in)",
           size = "Weight/height (lbs/in)",
           color = "Position")
  })
}
```
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
  output$plot1 <- renderPlot ({
    p <- df %>%
      filter(Position %in% input$groups,
             Position %in% input$position_select) %>%
      group_by(Position) %>%
      summarize(meanweight = mean(Weight),
                meanheight= mean(Height)) %>%
      ggplot(aes(x=meanweight, y=meanheight, size=(meanweight/meanheight), 
                 col=Position)) +
      labs(title = "Weight vs. Height per position",
           x = "Mean weight (lbs)", y = "Mean height (in)",
           size = "Weight/height (lbs/in)",
           color = "Position")
    for (i in 1:length(input$position_select)) {
      p <- p + 
        geom_point(data = filter(df, Position == input$position_select[i])) 
    }
    p
  })
````

```{r}
library(tidyverse)
basicstats <- read.csv("CSVnflbasicstats.csv")

dim(basicstats)
names(basicstats)
```
##Need to delete X column

```{r, echo=FALSE}
basicstats %>%
  filter(College == "Washington") %>%
  summarize(count = n())
```

```{r, echo=FALSE}
basicstats %>%
  filter(!is.na(College)) %>%
  group_by(College) %>%
  summarize(count = n()) %>%
  arrange(desc(rank(count)))
```

```{r}
library(lubridate)
monthdayyear <- as.Date(basicstats$Birthday, "%m/%d/%Y")
basicstats %>%
  mutate(birthdaymonth = month(as.Date(monthdayyear))) %>%
  filter(!is.na(monthdayyear)) %>%
  group_by(birthdaymonth) %>%
  summarize(count = n()) %>%
  ggplot(aes(x=birthdaymonth, y=count)) +
  geom_col() 

```
Most common birth month is January.


```{r, echo=FALSE}
defense <- basicstats %>%
  filter(Position == c("CB", "DB", "DE", "DL", "DT", "FS", "ILB", "LB", "MLB", "NT", "SAF", "SS")) %>%
  select(Height..inches., Position, Weight..lbs.)

offense <- basicstats %>%
filter(!is.na(Position),
         Position == c("C", "FB", "G", "OG", "OL", "OLB", "OT", "QB", "RB", "WR", "T", "TE")) %>%
  select(Height..inches., Position, Weight..lbs.)

specialteams <- basicstats %>%
  filter(!is.na(Position),
         Position == c("K", "LS", "P")) %>%
  select(Height..inches., Position, Weight..lbs.)

datacombined <- bind_rows(specialteams, offense, defense, .id = "Grouped Teams")
```

```{r, echo=FALSE}
datacombined %>%
  filter(is.na(Position) == FALSE, !is.na(Weight..lbs.),
         !is.na(Height..inches.)) %>%
  group_by(Position)%>%
  summarize(meanweight = mean(Weight..lbs.),
            meanheight= mean(Height..inches.)) %>%
  ggplot(aes(x=meanweight, y=meanheight, size=(meanweight/meanheight), 
             col=Position)) +
  geom_point() +
  labs(title = "Weight vs. Height per position",
         x = "Mean weight (lbs)", y = "Mean height (in)",
       size = "Weight/height (lbs/in)",
       color = "Position")
```
```{r}
datacombined %>%
  filter(is.na(Position) == FALSE, !is.na(Weight..lbs.)) %>%
  group_by(Position)%>%
  ggplot(aes(x=(Weight..lbs.))) + 
  geom_histogram(position = "dodge")
```
## how can i factor this by current status?!?!!??!





